services:
  mysql:
    image: mysql:8.4
    container_name: phrases-detective-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lazar2004
      MYSQL_DATABASE: phrases_detective
    ports:
      - "3306:3306"
    volumes:
      - phrases_detective_mysql:/var/lib/mysql

volumes:
  phrases_detective_mysql:
